#!/usr/bin/env bash

curl -ksL https://raw.githubusercontent.com/transcode-open/apt-cyg/master/apt-cyg > /bin/apt-cyg
chmod +x /bin/apt-cyg

apt-cyg update
apt-cyg install git vim zsh

curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

grep -q '/bin/zsh' /etc/nsswitch.conf || echo 'db_shell: /bin/zsh' >> /etc/nsswitch.conf

echo 'aWYgWyAtZiB+Ly5wcm9maWxlIF07IHRoZW4KCS4gfi8ucHJvZmlsZQpmaQo=' | base64 -d > ~/.bashrc

echo 'IyBlZGl0b3IKW1sgLXogJEVESVRPUiBdXSAmJiBleHBvcnQgRURJVE9SPXZpbQoKIyBTU0ggYWdl
bnQKZXhwb3J0IFNTSF9BVVRIX1NPQ0s9fi8uc3NoL3NzaC1hZ2VudC5zb2NrCnNzaC1hZGQgLWwg
Mj4vZGV2L251bGwgPi9kZXYvbnVsbAppZiBbICQ/IC1nZSAyIF07IHRoZW4KICBzc2gtYWdlbnQg
LWEgIiRTU0hfQVVUSF9TT0NLIiA+L2Rldi9udWxsCmZpCgo=' | base64 -d > ~/.profile

echo 'ZXhwb3J0IFpTSD0iJEhPTUUvLm9oLW15LXpzaCIKClpTSF9USEVNRT0iamlzcHdvc28iCgpwbHVn
aW5zPShnaXQpCgpzb3VyY2UgJFpTSC9vaC1teS16c2guc2gKCmlmIFsgLWYgfi8ucHJvZmlsZSBd
OyB0aGVuCgkuIH4vLnByb2ZpbGUKZmkK' | base64 -d > ~/.zshrc

echo 'c2V0IGZvcm1hdG9wdGlvbnMtPWNyCnNldCBjbGlwYm9hcmQ9dW5uYW1lZHBsdXMKc2V0IG1vdXNl
PXIK' | base64 -d > ~/.vimrc

mkdir -p ~/.ssh
echo 'c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFDQVFERFE1L0xqU1h1RXFrWUQzRW1ySGdnRnA5YlU4cXdxN3RqZVF5OUNZY0czTWwvZllPK0RPUStGbXBvRCtaUElXYTFzRTV4TWRYNjgxRXI2N2VjQzZRbjVIM3owcDJaSFhMMXFnTnpyTEFmVWJLMHhZbkYrajlEUFh2V1hqb0NjQVFpZG92N1lqNys0a3d4QkZFV0s5TWYwaG1neEp3UmJEWmMrM3FPUDU1bTN5aENPVVBvc0tDRk1JR1o1c0JkWE5xUGZWUCtJMFZqd3R3WWtETSs2OTRFOGxCR1NCZk0rNTZNd213S3BLbW52eDdxazI4SWNoT0ZGOFcxVzgyblFrdVVFQ1BwVWtVb2w1Q0JmYWJZQW5mbEdBRGZFSHIxNmlOY2Jra013NkZmUUtDWWpWMVF4Y0xnMnJEMGNtYXlLMlN6NFA3NCtTWUwxczd1aEFMUU5sZmtKaTBOajVET1JDOXhMeXZoYmlFZEJEZCtBbFdZTmp5ZUl5aVFWTFRKQzlPQTdEK2RjZkY4dWJjbVEzKzdIUmVpZTlRTmFURlcwSjBRMFVUcUNKV1RYazVETTN2UHdOR3BWU1hKdWRVTll3Y0FNL0g4Vng0aUpsYUdmbkNBNVpUTyt5QjdLalBSYU1lenBodi9mempHaUJIdkpydGphVk5hZGJGODhEWFpoZEYvOFNwVlhXN0RsdU04UThWbnZMdGgzOFEzcXJXMjd3dnVPNzViQ200bS9YRUlwOU5rRVVxRXh5QTdqTEFMUmZFQU1kUmZXb1lsaHFkUHpoMzFqNkkyTGtGL2tpZ3dNK25aUys5WFNXdk1LNmkvQUZ6T29nT1FXVnRlQVdTZTFwcGthRG8zYVY1WDRvVThjOHVBaVlMcHd4aVQ3b1lEbUlGYXIzcjJkalo0WlE9PSAvaG9tZS9qZmVycmFkYS8uc3NoL2lkX3JzYQo=' | base64 -d > ~/.ssh/authorized_keys
chmod 700 ~/.ssh
chmod 600 ~/.ssh/*
